// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashesController from "./flashes_controller"
application.register("flashes", FlashesController)

import GetController from "./get_controller"
application.register("get", GetController)

import ListController from "./list_controller"
application.register("list", ListController)
