require: rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 25
  Exclude:
     - 'db/**/*'
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
Layout/LineLength:
  Exclude:
    - 'config/**/*'
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'
Rails/I18nLocaleTexts:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
