require: rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 25
  Exclude:
     - 'db/**/*'
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
Layout/LineLength:
  Exclude:
    - 'config/**/*'
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'db/**/*'
    - 'app/helpers/application_helper.rb'
