name: CI/CD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.4'
          bundler-cache: true
      - name: Run Rubocop
        run: |
          bundle exec rubocop
      - name: Run RSpec
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: |
          sudo apt-get -yqq install libpq-dev
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rspec spec
